-- Hyprland Lua config
-- https://wiki.hypr.land/Configuring/Start/
-- Legacy hyprlang backup: hyprland.conf

hl.config({ autogenerated = false })

--- Returns connected monitor names from `hyprctl monitors`.
--- @return string[]
local function get_monitors()
  local f = io.popen("hyprctl monitors")
  if f == nil then
    return {}
  end
  local output = f:read("*a") or ""
  f:close()
  local names = {}
  for name in string.gmatch(output, "Monitor ([^%s]+) %(") do
    names[#names + 1] = name
  end
  return names
end

local function get_hostname()
  local f = io.popen("/bin/hostnamectl hostname")
  if f == nil then
    return nil
  end
  local hostname = f:read("*a") or ""
  f:close()
  hostname = string.gsub(hostname, "\n$", "")
  return hostname
end

local hostname = get_hostname() or "biluka"

--- Applies a configuration function based on the current hostname.
--- @param f1 fun(): nil  -- Configuration function for "biluka"
--- @param f2 fun(): nil  -- Configuration function for "pavi"
local function apply_invariant(f1, f2)
  if hostname == "biluka" then
    f1()
  elseif hostname == "pavi" then
    f2()
  end
end


local monitors = get_monitors()
apply_invariant(
  function()
        hl.monitor({
          output   = "HDMI-A-1",
          mode     = "1920x1080@144.00",
          position = "0x0",
          scale    = 1.0,
        })
  end,
  function()
    hl.monitor({
      disabled = false,
      output   = "DP-1",
      mode     = "2560x1440@100",
      position = "0x0",
      scale    = 1.0,
    })

    hl.monitor({
      disabled = true,
      output   = "eDP-1",
      mode     = "1920x1080@60",
      position = "0x0",
      scale    = 1.0,
    })
  end
)

---------------------
---- MY PROGRAMS ----
---------------------

local terminal    = "alacritty"
local fileManager = "dolphin"
local menu        = "qs -c noctalia-shell ipc call launcher toggle"
local lock        = "swaylock -k -l"

-------------------
---- AUTOSTART ----
-------------------


hl.on("hyprland.start", function()
  hl.exec_cmd("nm-applet")
  hl.exec_cmd("hyprsunset -g 100 -t 5000")
  hl.exec_cmd("hyprpaper")
  hl.exec_cmd("qs -c noctalia-shell")
  hl.exec_cmd("gnome-keyring-daemon --start --components=pkcs11,secrets,ssh")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_SIZE", "15")
hl.env("HYPRCURSOR_SIZE", "15")
hl.env("XMODIFIERS", "@im=fcitx")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")

-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
  general = {
    gaps_in          = 0,
    gaps_out         = 0,
    border_size      = 2,
    col              = {
      active_border   = "rgba(76,120,153,1)",
      inactive_border = "rgba(595959aa)",
    },
    resize_on_border = false,
    allow_tearing    = false,
    layout           = "dwindle",
  },
  cursor = {
    no_warps = true,
  },
  decoration = {
    rounding         = 0,
    rounding_power   = 0,
    active_opacity   = 1.0,
    inactive_opacity = 1.0,
    shadow           = { enabled = false },
    blur             = { enabled = false },
  },
  animations = {
    enabled = false,
  },
  dwindle = {
    preserve_split = true,
    force_split    = 2,
  },
  master = {
    new_status = "master",
  },
  misc = {
    force_default_wallpaper = 0,
    disable_hyprland_logo   = true,
    focus_on_activate       = false,
  },
  binds = {
    workspace_back_and_forth = false,
  },
})

---------------
---- INPUT ----
---------------

hl.config({
  input = {
    kb_layout    = "us,ara",
    kb_variant   = "",
    kb_model     = "",
    kb_options   = "grp:alt_shift_toggle",
    kb_rules     = "",
    repeat_rate  = 35,
    repeat_delay = 200,
    follow_mouse = 1,
    sensitivity  = 0,
    touchpad     = {
      natural_scroll = false,
    },
  },
})

-- hl.gesture({
--     fingers   = 3,
--     direction = "horizontal",
--     action    = "workspace",
-- })

hl.device({
  name        = "epic-mouse-v1",
  sensitivity = -0.5,
})

---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER"


hl.bind(mainMod .. " + return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exit())
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + E", hl.dsp.layout("togglesplit"))
-- fullscreenstate 2 -1: Hypr fullscreen without forcing client presentation mode (Brave etc.)
hl.bind(mainMod .. " + F", function()
  local w = hl.get_active_window()
  if not w then
    return
  end

  if w.fullscreen ~= 0 then
    hl.dispatch(hl.dsp.window.fullscreen_state({ internal = 0, client = 0, action = "set" }))
  else
    hl.dispatch(hl.dsp.window.fullscreen_state({ internal = 2, client = -1, action = "set" }))
  end
end)
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.float({ action = "toggle" }))

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + semicolon", hl.dsp.focus({ direction = "down" }))

for i = 1, 10 do
  local key = i % 10
  hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
  hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i, follow = false }))
end

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind(mainMod .. " + SHIFT + h", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + l", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + k", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + j", hl.dsp.window.move({ direction = "down" }))

apply_invariant(
  function()
    hl.bind(mainMod .. " + escape", hl.dsp.focus({ workspace = "previous" }))
  end,
  function()
    hl.bind(mainMod .. " + grave", hl.dsp.focus({ workspace = "previous" }))
  end
)
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload && killall waybar && waybar &"))
hl.bind("CTRL + ALT + Q", hl.dsp.exec_cmd(lock), { locked = true })

hl.bind("SHIFT + F11", hl.dsp.exec_cmd('grim -g "$(slurp -d)" - | wl-copy'))
hl.bind("SHIFT + F12",
  hl.dsp.exec_cmd('grim -g "$(slurp)" ~/media/screenshots/screenshot_$(date +%Y-%m-%d_%H-%M-%S).png'))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
  { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

hl.window_rule({
  name           = "suppress-maximize-events",
  match          = { class = ".*" },
  suppress_event = "maximize",
})

hl.window_rule({
  name     = "fix-xwayland-drags",
  match    = {
    class      = "^$",
    title      = "^$",
    xwayland   = true,
    float      = true,
    fullscreen = false,
    pin        = false,
  },
  no_focus = true,
})

hl.window_rule({
  name     = "brave-bitwarden-login-popup",
  match    = {
    class      = "^Brave.*$",
    float      = true,
    fullscreen = false,
    pin        = false,
  },
  no_focus = false,
  })

