[shell]
program = "/bin/zsh"
args = ["-l"]

[env]
TERM="xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations_theme_variant="Light"
opacity=1

[font]
size=9

# Default colors
[colors.primary]
background = '#161616'
foreground = '#f2f4f8'


# Carbonfox
[colors.normal]
black   = '#282828'
red     = '#ee5396'
green   = '#25be6a'
yellow  = '#08bdba'
blue    = '#78a9ff'
magenta = '#be95ff'
cyan    = '#33b1ff'
white   = '#dfdfe0'

# Bright colors
[colors.bright]
black   = '#484848'
red     = '#f16da6'
green   = '#46c880'
yellow  = '#2dc7c4'
blue    = '#8cb6ff'
magenta = '#c8a5ff'
cyan    = '#52bdff'
white   = '#e4e4e5'
